# Generated by Django 3.2.15 on 2022-09-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='Maintainer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Maintainer'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='file',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='site',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='update_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Update_date'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='video',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='author_book', to='librarian.Books', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='作者名称'),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_description',
            field=models.TextField(blank=True, null=True, verbose_name='图书简介'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_inventory',
            field=models.IntegerField(blank=True, null=True, verbose_name='图书库存'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='图书名称'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_num',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='图书编号'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_price',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='图书价格'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_sales',
            field=models.IntegerField(blank=True, null=True, verbose_name='图书销量'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图书评分'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='图书类型'),
        ),
        migrations.AlterField(
            model_name='books',
            name='comment_nums',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='评论量'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.publisher', verbose_name='出版社名称'),
        ),
        migrations.AlterField(
            model_name='image',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.books', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_address',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_label',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, choices=[('DT', 'DT'), ('TV', 'TV'), ('PD', 'PD')], max_length=128, null=True, verbose_name='OP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='librarian.Books', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码'),
        ),
    ]
