# Generated by Django 4.1.1 on 2022-09-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_auto_20220918_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='视频路径')),
                ('video_label', models.CharField(blank=True, max_length=128, null=True, verbose_name='视频名称')),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.books', verbose_name='图书')),
            ],
        ),
    ]
