# Generated by Django 4.1.1 on 2022-09-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='考试路径')),
                ('test_label', models.CharField(blank=True, max_length=128, null=True, verbose_name='考试名称')),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.books', verbose_name='图书')),
            ],
        ),
    ]
