# Generated by Django 4.1.1 on 2022-09-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='achievement',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='成绩'),
        ),
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='状态'),
        ),
    ]
