# Generated by Django 3.2 on 2022-09-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_auto_20220925_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, to='librarian.Books', verbose_name='图书'),
        ),
    ]
