# Generated by Django 3.2 on 2022-09-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_librarian_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='book',
        ),
    ]
