# Generated by Django 3.2 on 2022-09-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0009_librarian_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='book',
        ),
        migrations.AddField(
            model_name='librarian',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.books', verbose_name='图书'),
        ),
    ]
