# Generated by Django 3.2 on 2022-09-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0012_auto_20220925_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='books',
        ),
        migrations.AddField(
            model_name='books',
            name='librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.librarian', verbose_name='图书'),
        ),
    ]
