# Generated by Django 3.2 on 2022-09-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0014_auto_20220925_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='books',
        ),
        migrations.AddField(
            model_name='librarian',
            name='books_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='bookid'),
        ),
    ]
