# Generated by Django 3.2 on 2022-09-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0015_auto_20220925_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='userId')),
                ('book_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='bookId')),
            ],
        ),
    ]
