# Generated by Django 3.2 on 2022-09-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0016_userbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='books_id',
        ),
    ]
