# Generated by Django 3.2 on 2022-09-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0017_remove_librarian_books_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='achievement',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='成绩'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='状态'),
        ),
    ]
