# Generated by Django 3.2 on 2022-09-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0018_auto_20220925_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.books', verbose_name='图书'),
        ),
    ]
