# Generated by Django 3.2 on 2022-09-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0019_userbook_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='books',
        ),
    ]
