# Generated by Django 3.2 on 2022-09-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0020_remove_userbook_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件路径')),
                ('file_label', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件名称')),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.books', verbose_name='图书')),
            ],
        ),
    ]
