# Generated by Django 3.2 on 2022-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0021_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='answer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='标准答案'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='user_answer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='学生答案'),
        ),
    ]
